version: "3.6"

services:

  #######################################################
  ##    Voice
  #######################################################

  # Voice produce service - generates wav/mp3 file with voiced phrases.
  # Example: http://localhost:7050/say?text=крутая+озвучка&voice=anna
  # RHVoice available voice names:
  # alan            # English
  # aleksandr|anna  # Russian
  # anatol|natalia  # Ukrainian
  rhvoice_rest:
    build: speech/rhvoice_rest_simple
    ports:
      - 7050:8080
    environment:
      DEFAULT_VOICE: aleksandr

  # Speaker service - plays sounds (using VLC player).
  # It sends request to voice produce service and plays received wav/mp3 file.
  # Example: http://localhost:8050/say?text=класна+озвучка&lang=uk
  # Supported languages: uk, ru, en
  # Important! To hear the sound, connect your device to speakers or headphones.
  # In Windows or MacOS you could run this service manually without Docker: pip install -r requirements.txt && python main.py
  speaker:
    build: speech/speaker
    ports:
      - 8050:8080
    environment:
      RHVOICE_API_URL: http://rhvoice_rest:8080
      CONFIG_API_URL: http://config_provider:8080
    devices:
      # This service uses sound device in Linux, so it won't run in Windows or MacOS.
      - /dev/snd
    depends_on:
      - rhvoice_rest

  #######################################################
  ##    Core services
  #######################################################

  # CouchDB database.
  # Stores other services configurations.
  couchdb:
    image: couchdb:3.1
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    volumes:
      - couchdb_data:/opt/couchdb/data
    ports:
      - 5984:5984

  # Store and provide configuration for all applications
  # Example:
  #  - store default configs or get existing: POST http://localhost:8010/config/init/MY_APP_NAME  <json config in payload>
  config_provider:
    build: config_provider
    ports:
      - 8010:8080
    environment:
      DB_HOST: couchdb
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      - couchdb

  #######################################################
  ##    Applications
  #######################################################

  # Alarm clock. Speaks phrases at the specified time.
  # It's a default example application to demonstrate how the entire system works
  app_time_notify:
    build: app_time_notify
    environment:
      SPEAKER_API_URL: http://speaker:8080
      CONFIG_API_URL: http://config_provider:8080
    depends_on:
      - config_provider


volumes:
  couchdb_data:
